### ISSUE TITLE
Khan panics on create game without all parameters in JSON

### ISSUE THREAD

**Issue by traysh** [topfreegames/khan#4]
when calling:
```
curl -H "Content-Type: application/json" -X POST -d '{"name":"game","metadata":{}}' http://localhost:5530/games
```
docker log:
```
Created temporary directory /tmp/migrations096685914.
Wrote migration file 20160729184159_CreateCooldownAfterInviteField.sql.
Wrote migration file 20160608174439_CreateClanTable.sql.
Wrote migration file 20160621161411_CreateHooksTable.sql.
Wrote migration file 20160627155249_CreatePlayerMembershipAndOwnershipCount.sql.
Wrote migration file 20160728180524_CreateMaxPendingInvitesField.sql.
Wrote migration file 20160608133902_CreateGameTable.sql.
Wrote migration file 20160713191703_CreateMembershipDenierField.sql.
Wrote migration file 20160728195902_CreateMembershipMessageField.sql.
Wrote migration file 20160713185332_CreateGameCooldownAfterDenyAndDelete.sql.
Wrote migration file 20160819145352_CreateHookTriggerFieldsMetadata.sql.
Wrote migration file 20160608182307_CreateMembershipTable.sql.
Wrote migration file 20160627110742_LoadUUIDModule.sql.
Wrote migration file 20160627153918_CreateRetrieveClanIndexes.sql.
Wrote migration file 20160708161944_CreateMembershipApproverField.sql.
Wrote migration file 20160608150958_CreatePlayerTable.sql.
Wrote migration file 20160628181530_CreateClanMembershipCount.sql.
Wrote migration file 20160708192007_CreateOwnerIndex.sql.

Connecting to postgres:5432 as khan using sslMode=disable to db khan...

goose: no migrations to run. current version: 20160819145352
Migrated database successfully to version 20160819145352.
{"level":"info","ts":1495146882.3548918,"msg":"Loaded config file successfully.","source":"app","operation":"loadConfiguration","configPath":"/go/src/github.com/topfreegames/khan/config/default.yaml"}
{"level":"info","ts":1495146882.3560848,"msg":"Configuring sentry with URL ","source":"app","operation":"configureSentry"}
{"level":"info","ts":1495146882.357123,"msg":"New Relic is not enabled..","source":"app","appName":"khan","operation":"configureNewRelic"}
{"level":"info","ts":1495146882.3575394,"msg":"Initialized New Relic successfully.","source":"app","appName":"khan","operation":"configureNewRelic"}
{"level":"info","ts":1495146882.5288424,"msg":"Connected to database successfully.","source":"app","operation":"connectDatabase","host":"postgres","user":"khan","dbName":"khan","port":5432,"sslMode":"disable"}
{"level":"info","ts":1495146882.5301151,"msg":"Dispatcher initialized successfully","source":"app","operation":"initDispatcher"}
{"level":"info","ts":1495146882.5301428,"msg":"ES Worker initialized successfully","source":"app","operation":"initESWorker"}
{"level":"info","ts":1495146882.5312474,"msg":"Worker configured.","source":"dispatcher","operation":"Configure","workerCount":5,"redisHost":"redis","redisPort":6379,"redisDatabase":0,"redisPool":30}
{"level":"error","ts":1495146910.7659552,"msg":"Loading payload failed.","source":"gameHandler","operation":"updateGame","gameID":":1","error":"EOF"}
{"level":"error","ts":1495146910.7664812,"msg":"Failed to retrieve parameters.","source":"gameHandler","operation":"updateGame","gameID":":1","error":"EOF"}
{"level":"warn","ts":1495146910.7669663,"msg":"Request failed.","source":"request","route":"UpdateGame","endTime":1495146910.7668662,"statusCode":400,"latency":1227368,"ip":"172.20.0.1:60460","method":"PUT","path":"/games/:gameID"}
{"level":"error","ts":1495146917.7026482,"msg":"Panic occurred.","source":"app","panicText":"runtime error: index out of range","stack":"goroutine 19 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
/usr/local/go/src/runtime/debug/stack.go:24 +0x80 github.com/topfreegames/khan/api.(*RecoveryMiddleware).Serve.func1.1(0xc820024300, 0x7f94698e9588, 0xc8201ec120)
/go/src/github.com/topfreegames/khan/api/middleware.go:178 +0x1a0 panic(0xe9f620, 0xc820010060)
/usr/local/go/src/runtime/panic.go:443 +0x4e9 github.com/topfreegames/khan/api.(*UpdateGamePayload).Validate(0xc8201ee380, 0x0, 0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/payload.go:199 +0x426 github.com/topfreegames/khan/api.LoadJSONPayload(0xee54e0, 0xc8201ee380, 0x7f94698e9588, 0xc8201ec120, 0x7f946996b370, 0xc82020c360, 0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/helpers.go:89 +0x63e github.com/topfreegames/khan/api.UpdateGameHandler.func1.1(0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/game.go:116 +0x126 github.com/topfreegames/khan/api.WithSegment(0x1023f88, 0x7, 0x7f94698e9588, 0xc8201ec120, 0xc8200c8b48, 0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/helpers.go:152 +0x14a github.com/topfreegames/khan/api.UpdateGameHandler.func1(0x7f94698e9588, 0xc8201ec120, 0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/game.go:113 +0x82e github.com/topfreegames/khan/vendor/github.com/labstack/echo.(*Echo).add.func1(0x7f94698e9588, 0xc8201ec120, 0x0, 0x0)
/go/src/github.com/topfreegames/khan/vendor/github.com/labstack/echo/echo.go:475 +0xa9 github.com/topfreegames/khan/api.getBodyFromNext(0x7f94698e9588, 0xc8201ec120, 0xc8201bf110, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/middleware.go:32 +0x1e8 github.com/topfreegames/khan/api.(*BodyExtractionMiddleware).Serve.func1(0x7f94698e9588, 0xc8201ec120, 0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/middleware.go:48 +0x4a github.com/topfreegames/khan/api.(*LoggerMiddleware).Serve.func1(0x7f94698e9588, 0xc8201ec120, 0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/middleware.go:216 +0x40a github.com/topfreegames/khan/api.(*SentryMiddleware).Serve.func1.1(0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/middleware.go:93 +0x69 github.com/topfreegames/khan/api.WithSegment(0x10e7660, 0x11, 0x7f94698e9588, 0xc8201ec120, 0xc8200c94e8, 0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/helpers.go:152 +0x14a github.com/topfreegames/khan/api.(*SentryMiddleware).Serve.func1(0x7f94698e9588, 0xc8201ec120, 0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/middleware.go:123 +0x8a github.com/topfreegames/khan/api.(*VersionMiddleware).Serve.func1.1(0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/middleware.go:72 +0x372 github.com/topfreegames/khan/api.WithSegment(0x10e7680, 0x12, 0x7f94698e9588, 0xc8201ec120, 0xc8200c96b8, 0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/helpers.go:152 +0x14a github.com/topfreegames/khan/api.(*VersionMiddleware).Serve.func1(0x7f94698e9588, 0xc8201ec120, 0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/middleware.go:73 +0x9a github.com/topfreegames/khan/api.(*RecoveryMiddleware).Serve.func1(0x7f94698e9588, 0xc8201ec120, 0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/middleware.go:183 +0x83 github.com/topfreegames/khan/api.(*NewRelicMiddleware).Serve.func1(0x7f94698e9588, 0xc8201ec120, 0x0, 0x0)
/go/src/github.com/topfreegames/khan/api/middleware.go:286 +0x386 github.com/topfreegames/khan/vendor/github.com/labstack/echo.(*Echo).ServeHTTP.func1(0x7f94698e9588, 0xc8201ec120, 0x0, 0x0)
/go/src/github.com/topfreegames/khan/vendor/github.com/labstack/echo/echo.go:556 +0x1bb github.com/topfreegames/khan/vendor/github.com/labstack/echo.(*Echo).ServeHTTP(0xc8200f1c30, 0x7f94698e93c8, 0xc8201625c0, 0x7f94698e94a0, 0xc82020c060)
/go/src/github.com/topfreegames/khan/vendor/github.com/labstack/echo/echo.go:565 +0x2f9 github.com/topfreegames/khan/vendor/github.com/labstack/echo/engine/standard.(*Server).ServeHTTP(0xc82007b7a0, 0x7f94698e92d0, 0xc820212340, 0xc8202100e0)
/go/src/github.com/topfreegames/khan/vendor/github.com/labstack/echo/engine/standard/server.go:156 +0x636 net/http.serverHandler.ServeHTTP(0xc8201de180, 0x7f94698e92d0, 0xc820212340, 0xc8202100e0)
/usr/local/go/src/net/http/server.go:2081 +0x19e net/http.(*conn).serve(0xc8201e6300)
/usr/local/go/src/net/http/server.go:1472 +0xf2e created by net/http.(*Server).Serve
/usr/local/go/src/net/http/server.go:2137 +0x44e "}
```

**Comment by traysh** [comment]
This problem only occurs when HTTP method is POST

**Comment by leonardo2204** [comment]
Hey @traysh, I'm really sorry for the very long reply.
I've just opened PR #86 to fix this issue!

Thanks for reporting

**Comment by leonardo2204** [comment]
Just merged in master! We will launch a tag with the fix soon!
Thanks
